query GetServicesItem($id: ID!) {
  services_by_id(id: $id) {
    title

    slider {
      ...SliderFragment
    }

    serviceItemBlock {
      id

      directions_id {
        ...DirectionsFragment
      }
    }
  }
}
