query GetServicesItem($id: ID!) {
  services_by_id(id: $id) {
    title

    slider {
      ...SliderFragment
    }

    serviceItemDirections {
      id
      item {
        ... on directions {
          ...DirectionsFragment
        }

        ... on accordionsSection {
          ...AccordionsFragment
        }
      }
    }
  }
}
